<?php 
namespace VanguardLTE\Games\XocDiaGP
{
    use VanguardLTE\Http\Controllers\Web\GameProviders\GamePlayController;
    class Server
    {
        public  $GAMEID = 13;
        public  $GAMENAME = 'xocdia';
        public  $SELF_GEN_TREND = false;
        public  $GAME_TIME = 20;
        public  $GAME_PERIOD = 30;
        public  $LAST_LIMIT_TIME = 3;
        public  $RATE = [
            1 => 1.95, //odd
            2 => 1.95,  //even
            3 => 1.98,  //big
            4 => 1.98,  //small
            5 => 15,  //white4
            6 => 15,  //red4
            7 => 3.8, //white3
            8 => 3.8, //red3
        ];
        public  $MULTILIMIT = [
            [
                'lo' => 150,
                'hi' => 300000,
            ],
            [
                'lo' => 750,
                'hi' => 750000,
            ],
            [
                'lo' => 1500,
                'hi' => 1500000,
            ]
        ];

        public  $AFMT = '4x1';

        public $RESULT_LIST = [ //generated By genResultList()
            '2|4|5|0' => [
                "1|1|1|1",
                ],
            '1|4|0|7' => [
                "1|1|1|2",
                "1|1|2|1",
                "1|2|1|1",
                "2|1|1|1",
                ],
            '2|0|0|0' => [
                "1|1|2|2",
                "1|2|1|2",
                "1|2|2|1",
                "2|1|1|2",
                "2|1|2|1",
                "2|2|1|1",
                ],
            '1|3|0|8' => [
                "1|2|2|2",
                "2|1|2|2",
                "2|2|1|2",
                "2|2|2|1",
                ],
            '2|3|6|0' => [
                "2|2|2|2",
                ],
        ];

        public static function genResultList()
        {
            $totalResult = [
            ];
            for ($r1=1;$r1<=2;$r1++)
            {
                for ($r2=1;$r2<=2;$r2++)
                {
                    for ($r3=1;$r3<=2;$r3++)
                    {
                        for ($r4=1;$r4<=2;$r4++)
                        {   
                            $result = "$r1|$r2|$r3|$r4";
                            $rt = '';
                            $sum = $r1 + $r2 + $r3 + $r4;
                            //check odd / even
                            if ($sum % 2 == 0 )
                            {
                                $rt = '2';
                            }
                            else
                            {
                                $rt = '1';
                            }

                            //check big / small
                            if ($sum  < 6 )
                            {
                                $rt = $rt . '|4';
                            }
                            else if ($sum  > 6)
                            {
                                $rt = $rt . '|3';
                            }
                            else
                            {
                                $rt = $rt . '|0';
                            }

                            //check red4 / white4
                            if ($sum  == 4 )
                            {
                                $rt = $rt . '|5';
                            }
                            else if ($sum  == 8)
                            {
                                $rt = $rt . '|6';
                            }
                            else
                            {
                                $rt = $rt . '|0';
                            }

                            //check red3 / white3
                            if ($sum  == 5 )
                            {
                                $rt = $rt . '|7';
                            }
                            else if ($sum  == 7)
                            {
                                $rt = $rt . '|8';
                            }
                            else
                            {
                                $rt = $rt . '|0';
                            }
                            if (isset($totalResult[$rt])){
                                $totalResult[$rt][] = $result;
                            }
                            else
                            {
                                $totalResult[$rt] = [$result];
                            }
                        }
                    }
                }
            }
            return $totalResult;
        }
        public function generateResult($totalBet=0, $betStats=null)
        {
            $rts = array_keys($this->RESULT_LIST);
            if ($betStats != null)
            {
                $balance = [];
                foreach ($rts as $c)
                {
                    $wr = explode('|', $c);
                    $sum = 0;
                    foreach ($wr as $r)
                    {
                        $sum = $sum + $betStats[$r];
                    }
                    $balance[$c] =$sum;
                }
                

                $totalWinAmount = array_sum(array_values($betStats));
                if ($totalWinAmount > 0)
                {
                    $new_rts = [];
                    foreach ($rts as $c)
                    {
                        if ($balance[$c] < $totalBet) //win amount must be less than totalBet
                        {
                            $new_rts[] = $c;
                        }
                    }
                    if (count($new_rts) > 0){
                        $rts = $new_rts;
                    }
                }
            }

            $cc = [];
            $total = 0;
            foreach ($rts as $t)
            {
                $c = count($this->RESULT_LIST[$t]);
                $total = $total + $c * $c;
                $cc[] = $total;
            }
            $rand = mt_rand(0, $total);
            $sel_idx = 0;
            foreach ($cc as $idx => $c)
            {
                if ($rand < $c)
                {
                    $sel_idx = $idx;
                    break;
                }
            }
            $rt = $rts[$sel_idx];
            $results = $this->RESULT_LIST[$rt];
            $result = $results[mt_rand(0,count($results)-1)];
            return [
                'rno' => $result,
                'rt' => $rt
            ];
        }

        public function processCurrentTrend()
        {
            $currTime = time();
            $currentTrend = \VanguardLTE\GPGameTrend::where('s',0)->where('p',$this->GAMEID)->orderby('sl')->first();
            if ($currentTrend && GamePlayController::gamePlayTimeFormat($currTime) > $currentTrend->e) {
                $game = \VanguardLTE\Game::where('name', 'XocDiaGP')->where('shop_id', 0)->first();
                $_obf_grantwin_count = $game->garant_win10;
                $_obf_winline_count = $game->winline10;
                $_obf_grantwin_count++;
                if ($game->rezerv != 0 && $_obf_winline_count <= $_obf_grantwin_count){ //black result
                    $betStat = [
                        0 => 0,
                        1 => 0,
                        2 => 0,
                        3 => 0,
                        4 => 0,
                        5 => 0,
                        6 => 0,
                        7 => 0,
                        8 => 0,
                    ];
                    $totalBets = \VanguardLTE\GPGameBet::where([
                        'p' => $currentTrend->p,
                        'dno' => $currentTrend->dno,
                        'status' => 0,
                    ])->groupby('rt')->selectRaw('rt, sum(amount) as amount, sum(amount * o) as payout')->get();
                    foreach ($totalBets as $stat)
                    {
                        $betStat[$stat->rt] = $stat->payout;
                    }
                    $trendResult = $this->generateResult($totalBets->sum('amount'), $betStat);

                    $_obf_grantwin_count = 0;
                    $game->winline10 = $this->getNewSpin($game);
                }
                else{
                    $trendResult = $this->generateResult();
                }
                $game->garant_win10 = $_obf_grantwin_count;
                $game->save();

                $currentTrend->update([
                    'rno' => $trendResult['rno'],
                    'rt' => $trendResult['rt'],
                    's' => 1,
                ]);
                $currentTrend = $currentTrend->fresh();

                $rts = explode('|', $trendResult['rt']);

                $totalBets = \VanguardLTE\GPGameBet::where([
                    'p' => $currentTrend->p,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                ])->whereIn('rt', $rts)->get();
                $users = [];
                foreach ($totalBets as $bet)
                {
                    $bet->update([
                        'win' => $bet->amount * $bet->o
                    ]);
                }

                //process special case
                if ($rts[0] == 2 && $rts[2] == 0) //red2,white2
                {
                    $specialBets = \VanguardLTE\GPGameBet::where([
                        'p' => $currentTrend->p,
                        'dno' => $currentTrend->dno,
                        'status' => 0,
                    ])->groupby('user_id')->selectRaw('user_id, GROUP_CONCAT(rt SEPARATOR  ",") as grt')->get();
                    foreach ($specialBets as $bet)
                    {
                        $user_bets = explode(',', $bet->grt);
                        
                    }
                }

                //update user balance and add game_stat
                $totalBets = \VanguardLTE\GPGameBet::where([
                    'p' => $currentTrend->p,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                ])->groupby('user_id')->selectRaw('user_id, sum(amount) as bet, sum(win) as win')->get();
                $category = \VanguardLTE\Category::where(['provider' => null, 'shop_id' => 0, 'href' => 'gameplay'])->first();
                
                foreach ($totalBets as $bet)
                {
                    $user = \VanguardLTE\User::where('id', $bet->user_id)->first();
                    if ($user)
                    {
                        $user->update([
                            'balance' => $user->balance + $bet->win
                        ]);
                        $user = $user->fresh();
                        \VanguardLTE\StatGame::create([
                            'user_id' => $user->id, 
                            'balance' => intval($user->balance), 
                            'bet' => $bet->bet, 
                            'win' => $bet->win, 
                            'game' =>  $currentTrend->game_id, 
                            'type' => 'table',
                            'percent' => 0, 
                            'percent_jps' => 0, 
                            'percent_jpg' => 0, 
                            'profit' => 0, 
                            'denomination' => 0, 
                            'shop_id' => $user->shop_id,
                            'category_id' => isset($category)?$category->id:0,
                            'game_id' => $game->original_id,
                            'roundid' => $currentTrend->p . '_' . $currentTrend->dno,
                        ]);
                    }
                }


                $totalBets = \VanguardLTE\GPGameBet::where([
                    'game_id' => $currentTrend->game_id,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                ])->update(['status' => 1]);
                $currentTrend->s = 6; // ???
                return $currentTrend;
            }

            return null;

        }

        public function getNewSpin($game)
        {
            $_obf_linecount = 10;
            $win = explode(',', $game->game_win->winline10);
            $number = rand(0, count($win) - 1);
            return $win[$number];
        }
        public function gameDetail(\VanguardLTE\StatGame $stat)
        {
            $rounds = explode('_',$stat->roundid);
            $dno = $rounds[1];
            $userbets = \VanguardLTE\GPGameBet::where([
                'p' => $this->GAMEID,
                'dno' => $dno,
                'user_id' => $stat->user_id
            ])->get();
            $trend = \VanguardLTE\GPGameTrend::where(
                [
                    'p' => $this->GAMEID,
                    'dno' => $dno
                ]
            )->first();
            return [
                'type' => 'gameplay',
                'result' => $trend,
                'bets' => $userbets,
                'stat' => $stat
            ];

        }
    }
}
