<?php 
namespace VanguardLTE\Games\TaiXiuGP
{
    use VanguardLTE\Http\Controllers\Web\GameProviders\GamePlayController;
    class Server
    {
        public  $GAMEID = 12;
        public  $GAMENAME = 'taixiu';
        public  $SELF_GEN_TREND = false;
        public  $GAME_TIME = 20;
        public  $GAME_PERIOD = 30;
        public  $LAST_LIMIT_TIME = 3;
        public  $RATE = [
            1 => 1.98,
            2 => 1.98
        ];
        public  $MULTILIMIT = [
            [
                'lo' => 150,
                'hi' => 150000,
            ],
            [
                'lo' => 7500,
                'hi' => 1500000,
            ],
            [
                'lo' => 15000,
                'hi' => 3000000,
            ]
        ];

        public  $AFMT = '3x1';
        
        public $RESULT_LIST = [ //generated By genResultList()
            0 => [
                "1|1|1",
                "2|2|2",
                "3|3|3",
                "4|4|4",
                "5|5|5",
                "6|6|6"],
            1 => [
                "1|4|6",
                "1|5|5",
                "1|5|6",
                "1|6|4",
                "1|6|5",
                "1|6|6",
                "2|3|6",
                "2|4|5",
                "2|4|6",
                "2|5|4",
                "2|5|5",
                "2|5|6",
                "2|6|3",
                "2|6|4",
                "2|6|5",
                "2|6|6",
                "3|2|6",
                "3|3|5",
                "3|3|6",
                "3|4|4",
                "3|4|5",
                "3|4|6",
                "3|5|3",
                "3|5|4",
                "3|5|5",
                "3|5|6",
                "3|6|2",
                "3|6|3",
                "3|6|4",
                "3|6|5",
                "3|6|6",
                "4|1|6",
                "4|2|5",
                "4|2|6",
                "4|3|4",
                "4|3|5",
                "4|3|6",
                "4|4|3",
                "4|4|5",
                "4|4|6",
                "4|5|2",
                "4|5|3",
                "4|5|4",
                "4|5|5",
                "4|5|6",
                "4|6|1",
                "4|6|2",
                "4|6|3",
                "4|6|4",
                "4|6|5",
                "4|6|6",
                "5|1|5",
                "5|1|6",
                "5|2|4",
                "5|2|5",
                "5|2|6",
                "5|3|3",
                "5|3|4",
                "5|3|5",
                "5|3|6",
                "5|4|2",
                "5|4|3",
                "5|4|4",
                "5|4|5",
                "5|4|6",
                "5|5|1",
                "5|5|2",
                "5|5|3",
                "5|5|4",
                "5|5|6",
                "5|6|1",
                "5|6|2",
                "5|6|3",
                "5|6|4",
                "5|6|5",
                "5|6|6",
                "6|1|4",
                "6|1|5",
                "6|1|6",
                "6|2|3",
                "6|2|4",
                "6|2|5",
                "6|2|6",
                "6|3|2",
                "6|3|3",
                "6|3|4",
                "6|3|5",
                "6|3|6",
                "6|4|1",
                "6|4|2",
                "6|4|3",
                "6|4|4",
                "6|4|5",
                "6|4|6",
                "6|5|1",
                "6|5|2",
                "6|5|3",
                "6|5|4",
                "6|5|5",
                "6|5|6",
                "6|6|1",
                "6|6|2",
                "6|6|3",
                "6|6|4",
                "6|6|5"],
                2 => [
                "1|1|2",
                "1|1|3",
                "1|1|4",
                "1|1|5",
                "1|1|6",
                "1|2|1",
                "1|2|2",
                "1|2|3",
                "1|2|4",
                "1|2|5",
                "1|2|6",
                "1|3|1",
                "1|3|2",
                "1|3|3",
                "1|3|4",
                "1|3|5",
                "1|3|6",
                "1|4|1",
                "1|4|2",
                "1|4|3",
                "1|4|4",
                "1|4|5",
                "1|5|1",
                "1|5|2",
                "1|5|3",
                "1|5|4",
                "1|6|1",
                "1|6|2",
                "1|6|3",
                "2|1|1",
                "2|1|2",
                "2|1|3",
                "2|1|4",
                "2|1|5",
                "2|1|6",
                "2|2|1",
                "2|2|3",
                "2|2|4",
                "2|2|5",
                "2|2|6",
                "2|3|1",
                "2|3|2",
                "2|3|3",
                "2|3|4",
                "2|3|5",
                "2|4|1",
                "2|4|2",
                "2|4|3",
                "2|4|4",
                "2|5|1",
                "2|5|2",
                "2|5|3",
                "2|6|1",
                "2|6|2",
                "3|1|1",
                "3|1|2",
                "3|1|3",
                "3|1|4",
                "3|1|5",
                "3|1|6",
                "3|2|1",
                "3|2|2",
                "3|2|3",
                "3|2|4",
                "3|2|5",
                "3|3|1",
                "3|3|2",
                "3|3|4",
                "3|4|1",
                "3|4|2",
                "3|4|3",
                "3|5|1",
                "3|5|2",
                "3|6|1",
                "4|1|1",
                "4|1|2",
                "4|1|3",
                "4|1|4",
                "4|1|5",
                "4|2|1",
                "4|2|2",
                "4|2|3",
                "4|2|4",
                "4|3|1",
                "4|3|2",
                "4|3|3",
                "4|4|1",
                "4|4|2",
                "4|5|1",
                "5|1|1",
                "5|1|2",
                "5|1|3",
                "5|1|4",
                "5|2|1",
                "5|2|2",
                "5|2|3",
                "5|3|1",
                "5|3|2",
                "5|4|1",
                "6|1|1",
                "6|1|2",
                "6|1|3",
                "6|2|1",
                "6|2|2",
                "6|3|1"],
        ];

        public static function genResultList()
        {
            $totalResult = [
                0 => [],
                1 => [],
                2 => []
            ];
            for ($r1=1;$r1<=6;$r1++)
            {
                for ($r2=1;$r2<=6;$r2++)
                {
                    for ($r3=1;$r3<=6;$r3++)
                    {
                        $result = "$r1|$r2|$r3";
                        $rt = 0;
                        if ($r1 == $r2 && $r2 == $r3)
                        {
                            $rt = 0;
                        }
                        else if (($r1+$r2+$r3)>=11)
                        {
                            $rt = 1;
                        }
                        else
                        {
                            $rt = 2;
                        }
                        $totalResult[$rt][] = $result;
                    }
                }
            }
            return $totalResult;
        }

        public function generateResult($betStats=null)
        {
            $selPercentage = mt_rand(0,100);
            if ($selPercentage < 2)
            {
                $rt = 0;
            }
            else if ($selPercentage < 51)
            {
                $rt = 1;
            }
            else
            {
                $rt = 2;
            }
            // $rt = mt_rand(0,2);
            if ($betStats != null)
            {
                if ($betStats[1] > $betStats[2])
                {
                    $rt = 2;
                }
                else if ($betStats[1] < $betStats[2])
                {
                    $rt = 1;
                }
                else //equal
                {
                    // $rt = mt_rand(0,2);
                }
            }
            $lenResult = count($this->RESULT_LIST[$rt]);

            $selResult = mt_rand(0,$lenResult-1);
            $result = $this->RESULT_LIST[$rt][$selResult];
            return [
                'rno' => $result,
                'rt' => $rt
            ];
        }

        public function processCurrentTrend()
        {
            $currTime = time();
            $currentTrend = \VanguardLTE\GPGameTrend::where('s',0)->where('p',$this->GAMEID)->orderby('sl')->first();
            if ($currentTrend && GamePlayController::gamePlayTimeFormat($currTime) > $currentTrend->e) {
                $game = \VanguardLTE\Game::where('name', 'TaiXiuGP')->where('shop_id', 0)->first();
                $_obf_grantwin_count = $game->garant_win10;
                $_obf_winline_count = $game->winline10;
                $_obf_grantwin_count++;
                if ($game->rezerv != 0 && $_obf_winline_count <= $_obf_grantwin_count){ //black result
                    $betStat = [
                        1 => 0,
                        2 => 0,
                    ];
                    $totalBets = \VanguardLTE\GPGameBet::where([
                        'p' => $currentTrend->p,
                        'dno' => $currentTrend->dno,
                        'status' => 0,
                    ])->groupby('rt')->selectRaw('rt, sum(amount * o) as payout')->get();
                    foreach ($totalBets as $stat)
                    {
                        $betStat[$stat->rt] = $stat->payout;
                    }
                    $trendResult = $this->generateResult($betStat);
                    $_obf_grantwin_count = 0;
                    $game->winline10 = $this->getNewSpin($game);
                }
                else{
                    $trendResult = $this->generateResult();
                }
                $game->garant_win10 = $_obf_grantwin_count;
                $game->save();
                $currentTrend->update([
                    'rno' => $trendResult['rno'],
                    'rt' => $trendResult['rt'],
                    's' => 1,
                ]);
                $currentTrend = $currentTrend->fresh();

                $totalBets = \VanguardLTE\GPGameBet::where([
                    'p' => $currentTrend->p,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                    'rt' => $currentTrend->rt
                ])->get();
                $users = [];
                foreach ($totalBets as $bet)
                {
                    $bet->update([
                        'win' => $bet->amount * $bet->o
                    ]);
                }

                //update user balance and add game_stat
                $totalBets = \VanguardLTE\GPGameBet::where([
                    'p' => $currentTrend->p,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                ])->groupby('user_id')->selectRaw('user_id, sum(amount) as bet, sum(win) as win')->get();
                $category = \VanguardLTE\Category::where(['provider' => null, 'shop_id' => 0, 'href' => 'gameplay'])->first();
                foreach ($totalBets as $bet)
                {
                    $user = \VanguardLTE\User::where('id', $bet->user_id)->first();
                    if ($user)
                    {
                        $user->update([
                            'balance' => $user->balance + $bet->win
                        ]);
                        $user = $user->fresh();
                        \VanguardLTE\StatGame::create([
                            'user_id' => $user->id, 
                            'balance' => intval($user->balance), 
                            'bet' => $bet->bet, 
                            'win' => $bet->win, 
                            'game' =>  $currentTrend->game_id, 
                            'type' => 'table',
                            'percent' => 0, 
                            'percent_jps' => 0, 
                            'percent_jpg' => 0, 
                            'profit' => 0, 
                            'denomination' => 0, 
                            'shop_id' => $user->shop_id,
                            'category_id' => isset($category)?$category->id:0,
                            'game_id' => $game->original_id,
                            'roundid' => $currentTrend->p . '_' . $currentTrend->dno,
                        ]);
                    }
                }


                $totalBets = \VanguardLTE\GPGameBet::where([
                    'game_id' => $currentTrend->game_id,
                    'dno' => $currentTrend->dno,
                    'status' => 0,
                ])->update(['status' => 1]);
                $currentTrend->s = 6; // ???
                return $currentTrend;
            }

            return null;

        }

        public function gameDetail(\VanguardLTE\StatGame $stat)
        {
            $rounds = explode('_',$stat->roundid);
            $dno = $rounds[1];
            $userbets = \VanguardLTE\GPGameBet::where([
                'p' => $this->GAMEID,
                'dno' => $dno,
                'user_id' => $stat->user_id
            ])->get();
            $trend = \VanguardLTE\GPGameTrend::where(
                [
                    'p' => $this->GAMEID,
                    'dno' => $dno
                ]
            )->first();
            return [
                'type' => 'gameplay',
                'result' => $trend,
                'bets' => $userbets,
                'stat' => $stat
            ];

        }
        public function getNewSpin($game)
        {
            $_obf_linecount = 10;
            $win = explode(',', $game->game_win->winline10);
            $number = rand(0, count($win) - 1);
            return $win[$number];
        }
    }
}
